@startuml

skinparam shadowing true


Item <|-- Character
IHero <|-- Character

Scene <|-- BattleScene
BattleScene *-left- Character
Character o-- BattleScene

Character o-- HeadEquipment
Character o-- LegEquipment
Character o-- Armor

Character <|-down- Link
Link <|-- CPlayer1
Link <|-- CPlayer2
CPlayer2 <|-- CAIPlayer

Character o-- MeleeWeapon
Character o-- Bow
Character o-- Arrow

' Weapon <|-- MeleeWeapon
' Weapon <|-- RangedWeapon

' RangedWeapon <|-- Bow
' RangedWeapon <|-- Arrow

@enduml
