@startuml

skinparam shadowing true

[*] --> NORMAL

NORMAL --> FIREING : Fire Attack
FIREING --> NORMAL : Timeout
NORMAL --> ICEING : Ice Attack
ICEING --> NORMAL : Timeout
NORMAL --> LIGHTNING : Lightning Attack
LIGHTNING --> NORMAL : Timeout

[*] --> HOLD
HOLD --> ATTACKING : AttackDown
ATTACKING --> HOLD : Timeout
HOLD --> HITTING : Be Attack
HITTING --> HOLD : Timeout

@enduml
