@startuml

skinparam shadowing true

[*] --> NORMAL_HOLD

NORMAL_HOLD --> NORMAL_ATTACKING : setAttack
NORMAL_HOLD --> NORMAL_HITTING : beNormalHit
NORMAL_HOLD --> FLAME_HITTING : beFlameHit
NORMAL_HOLD --> ICE_HITTING : beIceHit
NORMAL_HOLD --> ELECTRO_HITTING : beElectroHit
NORMAL_ATTACKING --> NORMAL_HOLD : timeout 500ms
NORMAL_HITTING --> NORMAL_HOLD : timeout 500ms

FLAME_HOLD --> FLAME_ATTACKING : setAttack
FLAME_HOLD --> FLAME_HITTING : beHit
FLAME_HOLD --> NORMAL_HOLD : timeout 10s
FLAME_ATTACKING --> FLAME_HOLD : timeout 500ms
FLAME_HITTING --> FLAME_HOLD : timeout 500ms

ICE_HOLD --> NORMAL_HITTING : beHit
ICE_HOLD --> NORMAL_HOLD : timeout 5s
ICE_HITTING --> ICE_HOLD : timeout 500ms

ELECTRO_HOLD --> ELECTRO_ATTACKING : setAttack
ELECTRO_HOLD --> ELECTRO_HITTING : beHit
ELECTRO_HOLD --> NORMAL_HOLD : timeout 5s
ELECTRO_ATTACKING --> ELECTRO_HOLD : timeout 500ms
ELECTRO_HITTING --> ELECTRO_HOLD : timeout 500ms




@enduml
