@startuml

skinparam shadowing true

[*] --> STATIC

[*] --> NORMAL
NORMAL --> BURNED
NORMAL --> BURNING : beFlameHit
BURNED --> NORMAL
BURNED --> BURNING
BURNING --> BURNOUT
BURNOUT --> [*]

@enduml
