@startuml

skinparam shadowing true

[*] --> FNORMAL

FNORMAL --> BURNED : beFlameTrans
FNORMAL --> BURNING : beFlameHit
BURNED --> BURNING : timeout 2s
BURNING --> BURNOUT : timeout 10s
BURNOUT --> [*]


[*] --> ENORMAL

ENORMAL --> SHOCKED : beElectroTrans
ENORMAL --> SHOCKING : beElectroHit
SHOCKED --> SHOCKING : timeout 500ms
SHOCKING --> SHOCKOUT : timeout 2s
SHOCKOUT --> ENORMAL : timeout 2500ms

@enduml
