@startuml

skinparam shadowing true

class MeleeWeapon {
}

MeleeWeapon <|-- TwoHandedSword
MeleeWeapon <|-- Spear
MeleeWeapon <|-- OneHandedSword

CWood <|-- WoodenOneHandedSword

OneHandedSword <|-- WoodenOneHandedSword
OneHandedSword <|-- MetalOneHandedSword

WoodenOneHandedSword <|-- NormalWoodenOneHandedSword
WoodenOneHandedSword <|-- FlameWoodenOneHandedSword
WoodenOneHandedSword <|-- IceWoodenOneHandedSword
WoodenOneHandedSword <|-- ElectroWoodenOneHandedSword

@enduml
